# Generated by Django 3.2.5 on 2021-07-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_baza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baza',
            old_name='databaseChoice',
            new_name='data_base_Choice',
        ),
        migrations.AddField(
            model_name='hops',
            name='mreza',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
