# Generated by Django 3.2.5 on 2021-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210809_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('user_types', models.IntegerField(choices=[(1, 'Admin'), (2, 'Director'), (3, 'Engineer')])),
            ],
        ),
    ]
