# Generated by Django 3.2.5 on 2021-08-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='HopsUser',
        ),
        migrations.DeleteModel(
            name='Baza',
        ),
        migrations.DeleteModel(
            name='Hops',
        ),
    ]
