# Generated by Django 3.2.5 on 2021-08-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_hopsuser_user_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopsuser',
            name='user_types',
        ),
    ]
